# Generated by Django 2.2 on 2019-04-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route_Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_departure', models.DateField()),
                ('time_arrive', models.DateField()),
                ('type', models.CharField(choices=[('Driver', 'Driver'), ('Passenger', 'Passenger')], max_length=20)),
                ('route_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Person')),
                ('streets', models.ManyToManyField(through='dms.Route_Street', to='dms.Streets')),
            ],
        ),
        migrations.AddField(
            model_name='route_street',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Routes'),
        ),
        migrations.AddField(
            model_name='route_street',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Streets'),
        ),
        migrations.CreateModel(
            name='R_S_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_S', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Route_Street')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Dialog')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Person')),
            ],
        ),
    ]
